name: Trigger Remote Cypress Workflow

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
      repo:
        description: 'Name of the repository in {owner}/{repository} format'
        required: true
      workflow_name:
        description: 'Name of the Github workflow yml file in the component repository'
        required: true
      os_url:
        description: 'Release artifact of OpenSearch'
        required: true
      osd_url:
        description: 'Release artifact of OpenSearch Dashboards'
        required: true
      branch_ref:
        description: 'Test branch name or commit reference id'
        required: true

env:
  GITHUB_SECRET_TOKEN: ${{ secrets.REMOTE_GITHUB_PAT }}
jobs:
  set-remote-cypress-token:
    runs-on: ubuntu-latest
    name: Run integtest script

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash Script
        run: |
          echo "Executing remoteCypress script for workflow_dispatch event"
          ./integtest.sh
      
      

        

